include_recipe "git"
include_recipe "zsh"
include_recipe "vim"
include_recipe "tmux"
include_recipe "nodejs"

include_recipe "parshap::user"
include_recipe "parshap::zsh"
include_recipe "parshap::dotfiles"
include_recipe "parshap::janus"
